### ISSUE TITLE
QtWidgets.QApplication.translate syntax error using PySide

### ISSUE THREAD

**Issue by elveatles** [mottosso/Qt.py#129]
The translate method is different between Qt4 and Qt5. 
You can try this Python code:

```
import sys

from Qt import QtWidgets

class MainWindow(QtWidgets.QWidget):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        title = QtWidgets.QApplication.translate("MainWindow", "MainWindow", None, -1)
        
def main():
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = MainWindow()
    mainWindow.show()
    app.exec_()

if __name__ == '__main__':
    main()
```

If I have PySide2, this will work. If I have PySide, I will get the error:

> TypeError: 'PySide.QtCore.QCoreApplication.translate' called with wrong argument types:
>   PySide.QtCore.QCoreApplication.translate(str, str, NoneType, int)
> Supported signatures:
>   PySide.QtCore.QCoreApplication.translate(str, str, str = None, PySide.QtCore.QCoreApplication.Encoding = CodecForTr)
>   PySide.QtCore.QCoreApplication.translate(str, str, str, PySide.QtCore.QCoreApplication.Encoding, int)

I was trying to compile .ui files like how it is being done in #88 compiling resources . And this always generates a bunch of translate lines.

**Comment by mottosso** [comment]
Thanks for reporting this @elveatles.

This is an area where I'm open to suggestions. It seems to me that the problem is compiling for a particular binding, and then attempting to run it on another. Does that sound about right?

One way to solve this might be to monkey patch the `QCoreApplication.translate` function. But the problem with this is that it breaks rule 3; co-existence with original bindings. That is, it may break non-Qt.py programs in subtle and unexpected ways.

I wonder whether a more cross-compatible way to handle this is first to compile the `ui` file into a `py` file, and perform some kind of post operation on it via Qt.py.

```bash
$ compile_ui my_widget.ui
$ Qt.py --convert my_widget.py
```

The post operation could *replace* the `translate` function with whatever it is expected to produce using some function that works across every binding.

Alternatively, if it's possible to somehow get to the generated code from the `loadUi` function and friends, and modify it *before* it executes.

Let me know what you think.

**Comment by elveatles** [comment]
For my own code, I ended up monkey patching the translate function. Even though it hasn't caused me problems yet, I am worried about unforeseen consequences. 

I do like the idea of using Qt.py --convert my_widget.py. Currently, I'm compiling with pyside2uic and then simply doing a replace(u'PySide2', u'Qt') on the compiled .py file. I find this a lot easier than trying to convert my existing code from using setupUi to loadUi.

Thanks for looking into this.

**Comment by mottosso** [comment]
> Currently, I'm compiling with pyside2uic and then simply doing a replace(u'PySide2', u'Qt') on the compiled .py file.

That may be all there is to it.

Qt.py is all about PySide2 compatibility, so whatever `pyside2uic` throws at it, it should be able to handle.

Do you think it would make sense to make this the only supported method of working with `.ui` files? Even for those working with PyQt4, or even PyQt5? That they (1) perform a conversion to `.py`, and (2) another conversion from PySide2 to Qt.py?

I know some prefer the in-memory method of `load_ui()`. Do you think there is any way of wrapping `pyside2uic` up in such a way that it *acts* like `load_ui()`, but runs through (1) and (2) implicitly?

**Comment by elveatles** [comment]
I think the choice of whether to compile .ui files or use load_ui should be left to the user since Qt bindings give you that choice as well.

**Comment by mottosso** [comment]
> I think the choice of whether to compile .ui files or use load_ui should be left to the user since Qt bindings give you that choice as well.

Agreed. Do you think it's reasonable to have Qt.py encourage compiling `.ui` files via `pyside2uic`, even for users working with other bindings?

That way, we can setup a "Compiling ui files with Qt.py" guide which would essentially be a PySide2 guide, with the added post-conversion to Qt.py.

**Comment by elveatles** [comment]
Yes, I think it would be great to have a compiling guide plus a post-conversion script. Since Qt.py does things the PySide2 way, it makes sense to use pyside2uic.

**Comment by hdd** [comment]
@elveatles please feel free to see if https://bitbucket.org/efestolab/qtext works for you.
Cheers.

**Comment by mottosso** [comment]
Hi @elveatles, let me know if this works for you.

- https://github.com/mottosso/Qt.py/releases/tag/0.5.0
