### ISSUE TITLE
Qt.QtCompat.translate error with PySide

### ISSUE THREAD

**Issue by elveatles** [mottosso/Qt.py#154]
Qt.QtCompat does not seem to work properly when using it with PySide. Here is the error I get:

> TypeError: 'PySide.QtCore.QCoreApplication.translate' called with wrong argument types:
>   PySide.QtCore.QCoreApplication.translate(str, str, NoneType, NoneType, int)
> Supported signatures:
>   PySide.QtCore.QCoreApplication.translate(str, str, str = None, PySide.QtCore.QCoreApplication.Encoding = CodecForTr)
>   PySide.QtCore.QCoreApplication.translate(str, str, str, PySide.QtCore.QCoreApplication.Encoding, int)

**Comment by mottosso** [comment]
Hi @elveatles, could you post what arguments you did put into the function, and what argumentts you expect to be able to put into it?

The required argument signature is the one from PySide2 which looks like this.

- https://github.com/mottosso/Qt.py/blob/master/Qt.py#L198

**Comment by elveatles** [comment]
I'm using the arguments that pyside2uic compiles.
Here's an example:
Qt.QtCompat.translate("FTrackTool", "Status", None, -1)

**Comment by s0217391** [comment]
Hi!

I have run into the same error just today. Trying to give as much info as I can:

compiled through pyside-uic:
self.open.setText(QtGui.QApplication.translate("atlasWidget", "Open", None, QtGui.QApplication.UnicodeUTF8))

compiled through pyside2-uic:
self.open.setText(QtWidgets.QApplication.translate("atlasWidget", "Open", None, -1))

converting pyside2-uic result with Qt conversion:
self.open.setText(Qt.QtCompat.translate("atlasWidget", "Open", None, -1))

Qt.QtCompat call for pyside (based on Qt.py source code):
QtCore.QCoreApplication.translate(context, sourceText, disambiguation, NONE (inserted), n)


Error message:
TypeError: 'PySide.QtCore.QCoreApplication.translate' called with wrong argument types:
  PySide.QtCore.QCoreApplication.translate(str, str, NoneType, NoneType, int)
Supported signatures:
  PySide.QtCore.QCoreApplication.translate(str, str, str = None, PySide.QtCore.QCoreApplication.Encoding = CodecForTr)
  PySide.QtCore.QCoreApplication.translate(str, str, str, PySide.QtCore.QCoreApplication.Encoding, int)

Pyside documentation for reference:
https://srinikom.github.io/pyside-docs/PySide/QtCore/QCoreApplication.html#PySide.QtCore.PySide.QtCore.QCoreApplication.translate

So it seems there is a pyside translate function with 5 parameters but simply injecting None doesn't work (bottom supported signature)
There is also a 4 parameter one that is not called because Qt.QtCompat is automatically calling the 5 parameter one (top supported signature)

For now, I have changed the QtCompat lambda to just 3 parameters (using the 4 parameter one with the default value for the last param). This around line 260:
	
	_add(QtCompat, "translate",
         lambda context, sourceText, disambiguation, n:
         QtCore.QCoreApplication.translate(context,
                                           sourceText,
                                           disambiguation,
                                           None,
                                           n))

To:
    _add(QtCompat, "translate",
         lambda context, sourceText, disambiguation, n:
         QtCore.QCoreApplication.translate(context,
                                           sourceText,
                                           disambiguation))

Which seems to work. I'd love to hear if there is a better fix.

Cheers,

Pj

**Comment by s0217391** [comment]
Oops, I saw your fix just too late. Sorry for the spam.

**Comment by mottosso** [comment]
Not spam at all, this great investigative info, thanks for that @s0217391!

The fix I pushed is an untested one, what I'd need is for you to take a look at it, and see if it solves your problem. If it does, then I'd like a simple test for it, something to make sure that a future developer doesn't accidentally break the feature.

Also, we'll need to make sure it works across all bindings. This is also where a test could help, as it could run on all of them at once.
