### ISSUE TITLE
`import Qt` breaks `from Qt import QtCore`

### ISSUE THREAD

**Issue by dbr** [mottosso/Qt.py#158]
Doing this works, of course:

```
>>> from Qt import QtCore
>>> QtCore.Signal
<type 'PyQt4.QtCore.pyqtSignal'>
>>>
```

However typical import mechanics should allow `import Qt.QtCore` also, but this fails to find patched `Signal` attribute:

```
>>> import Qt.QtCore
>>> Qt.QtCore.Signal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Signal'
>>> 
```

Even more confusingly, doing `import Qt.QtCore` breaks subsequent `from Qt import QtCore` calls (either in the same file or other .py files in the same module):

```
>>> import Qt.QtCore
>>> Qt.QtCore.Signal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Signal'
>>> from Qt import QtCore
>>> QtCore.Signal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Signal'
>>> 
```

This was particularly hard to debug as adding an import into one file broke an import and an unrelated file, e.g:

```
# go/__init__.py
import Qt.QtCore # Comment this and...
```
```
# go/mainwindow.py
import go.mywidgets
```
```
#go/mywidgets.py
from Qt import QtCore
print QtCore.Signal # ..this line stops erroring
```
then run `env PYTHONPATH=$PWD python -c import go.mainwindow`

I suspect this is due to how the Qt.py module modifies `sys.modules`. Perhaps `sys.modules["Qt"] = ...` only alters `from Qt import ...` but doesn't alter the behaviour of `import Qt.QtCore`?

**Comment by mottosso** [comment]
Thanks @dbr for reporting this.

Can you confirm which binding you are using?

```python
>>> import Qt
>>> print(Qt.QtCompat.__binding__)
'PySide'
```

I can reproduce the problem with PyQt4, it doesn't seem to happen with PySide however.

**Comment by mottosso** [comment]
The fix #159 looks to take care of it, let me know if you continue to experience the problem!

**Comment by mottosso** [comment]
For completeness, the problem was due to an internal detail of the Python import mechanism.

When `import Qt`, the remappings are made and the resulting binding with remapping is returned. On the other hand, when `import Qt.QtCore`, the remappings are made and garbage collected. They were stored alongside the binding, but the binding was not returned, hence it was garbage collected along with any attached members, causing `QtCore` to be *reimported* and thus appearing to lose remappings.

The solution was to explicitly append the members before returning control to Python.

- [Reference](https://github.com/mottosso/Qt.py/blob/b305f2b6570103c6985340676e18ee7a12726aea/Qt.py#L409)

The same problem occurred and was solved with QtWidgets, see #133 for details on that.

**Comment by dbr** [comment]
Ahh, I see! Shall test tomorrow, but sounds like that should fix it - thanks!

> Can you confirm which binding you are using?

The issue was happening with PyQt4 and 5

**Comment by dbr** [comment]
The fix worked, thanks!

**Comment by fredrikaverpil** [comment]
> For completeness, the problem was due to an internal detail of the Python import mechanism.

Tricky!
Good job hunting this down and fixing it. 👍
