### ISSUE TITLE
Universal wheel

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#162]
Edit 1: posted this prematurely (hotkey on commute...), please refresh!
Edit 2: structured up findings into one single post

### Goal

Offer one single, universal, wheel for Qt.py: `Qt.py-0.6.6-py2.py3-none-any.whl`.

### Background

I'm maintaining an internal wheel "registry" at my company and I recently realized there are one wheel for each major version of Python:

```
Qt.py-0.6.6-py2-none-any.whl
Qt.py-0.6.6-py3-none-any.whl
```

If you attempt to install e.g. the py3 version into Python 2.x you'll get this:

```bash
pip2 install Qt.py-0.6.6-py3-none-any.whl
Qt.py-0.6.6-py3-none-any.whl is not a supported wheel on this platform.
```

So far, I haven't looked into the pip deployment at all, but there seems to be a possibility to have Qt.py use one and the same wheel for either version, which would be nice. An example of another open source package doing this is [virtualenv](https://github.com/pypa/virtualenv). Here you can see only one wheel is available and it's called `virtualenv-15.1.0-py2.py3-none-any.whl`.

### Implementation

It seems we need to do two things:

1. Add `setup.cfg` with the following contents:

```
[bdist_wheel]
universal=1
```

2. Change [this line](https://github.com/mottosso/Qt.py/blob/master/.travis.yml#L26) of the Travis PyPi deployment into:

```
distributions: "sdist bdist_wheel"
```

Sources:
* https://wheel.readthedocs.io/en/latest/
* http://www.dougalmatthews.com/2016/Sep/01/automate-publishing-to-pypi-with-pbr-and-travis/
*  https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/

___

@mottosso I believe you have a better overall understanding (than me) on how the PyPi deployment works and how to test it out. Would you like to have a look at this? (there's absolutely no hurry on my part on getting this implemented)

**Comment by fredrikaverpil** [comment]
Hm. It seems like all we have to do is add `setup.cfg` with the following contents:

```
[bdist_wheel]
universal = 1
```

Please see [here](https://hynek.me/articles/sharing-your-labor-of-love-pypi-quick-and-dirty/) where he explains:

> The first part will make wheel build a universal wheel file (e.g. attrs-15.1.0-py2.py3-none-any.whl) and you won’t have to circle through virtual environments of all supported Python versions to build them separately.

This is also how virtualenv does it, it seems: https://github.com/pypa/virtualenv/blob/master/setup.cfg

**Comment by fredrikaverpil** [comment]
It's also possible we need to change [this line](https://github.com/mottosso/Qt.py/blob/master/.travis.yml#L26) of the Travis PyPi deployment into:

```
distributions: "sdist bdist_wheel"
```

**Comment by mottosso** [comment]
Thanks @fredrikaverpil, looks interesting. I have very little experiences with wheels, my understanding was that they are better (only?) suited for packages that contain binaries, and offer a way of providing identical sources with unique binaries per platform.

Since Qt.py has no binaries, I didn't think it applies.

But, having had a look at the [wheels documentation](https://packaging.python.org/distributing/#wheels) it appears they do apply, and what we're looking for is - as you say - a "universal wheel".

As for testing it out, you should be able to locally build a wheel and see how it works for you.

```bash
$ git clone
$ cd Qt.py
$ python setup.py bdist_wheel --universal
```

It should build a "universal" wheel for you, that you can later try out.

To have it automatically built and uploaded to PyPI, we'll have to pass through Travis, and some quick Googling didn't reveal how to accomplish this.

Simply adding `bdist_wheel` to our `.travis.yml` seem to only produce a "Pure Python Wheel", which isn't cross-compatible with Python 3.

From [the docs](https://packaging.python.org/distributing/#id66), it might be a combination of `bdist_wheel` and a new `setup.cfg` file that does the trick.

I'd be happy for you to try, the only way we can really be sure is by making a few releases and seeing what travis and PyPI says. If you can build it locally first and make sure there isn't anything in Qt.py that hinders the ability, that would be best.

**Comment by fredrikaverpil** [comment]
Sounds good, I'll look into this.

I just noticed these are the variants which can get downloaded from `pip wheel -w . Qt.py`:

```
Qt.py-0.6.6-py2-none-any.whl  # macOS
Qt.py-0.6.6-py3-none-any.whl  # macOS
Qt.py-0.6.6-cp27-none-any.whl   # Windows
Qt.py-0.6.6-cp35-none-any.whl  # Windows
```

**Comment by fredrikaverpil** [comment]
Ok, here we go:

```bash
$ python setup.py bdist_wheel --universal
running bdist_wheel
running build
running build_py
creating build
creating build/lib
copying Qt.py -> build/lib
installing to build/bdist.macosx-10.11-x86_64/wheel
running install
running install_lib
creating build/bdist.macosx-10.11-x86_64
creating build/bdist.macosx-10.11-x86_64/wheel
copying build/lib/Qt.py -> build/bdist.macosx-10.11-x86_64/wheel
running install_egg_info
running egg_info
creating Qt.py.egg-info
writing Qt.py.egg-info/PKG-INFO
writing top-level names to Qt.py.egg-info/top_level.txt
writing dependency_links to Qt.py.egg-info/dependency_links.txt
writing manifest file 'Qt.py.egg-info/SOURCES.txt'
reading manifest file 'Qt.py.egg-info/SOURCES.txt'
writing manifest file 'Qt.py.egg-info/SOURCES.txt'
Copying Qt.py.egg-info to build/bdist.macosx-10.11-x86_64/wheel/Qt.py-0.6.6-py2.7.egg-info
running install_scripts
creating build/bdist.macosx-10.11-x86_64/wheel/Qt.py-0.6.6.dist-info/WHEEL
```

This resulted in:

```bash
$ tree dist
dist
└── Qt.py-0.6.6-py2.py3-none-any.whl

0 directories, 1 file
```

Tried to pip install it:

```bash
$ pip2 --version
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
```
```bash
$ pip2 install dist/Qt.py-0.6.6-py2.py3-none-any.whl 
Processing ./dist/Qt.py-0.6.6-py2.py3-none-any.whl
Installing collected packages: Qt.py
Successfully installed Qt.py-0.6.6
```

```bash
$ pip3 --version
pip 9.0.1 from /usr/local/lib/python3.5/site-packages (python 3.5)
```
```bash
$pip3 install dist/Qt.py-0.6.6-py2.py3-none-any.whl
Processing ./dist/Qt.py-0.6.6-py2.py3-none-any.whl
Installing collected packages: Qt.py
Successfully installed Qt.py-0.6.6
```

What do you think, should I create a PR and we can try this out with Travis?

All I did was the two things outlined in my initial post:
* Add setup.cfg
* Add `bdist_wheel` to Travis config

**Comment by mottosso** [comment]
Yes, put together a PR. We'll have to make releases as well, to get it to upload to PyPI so that you can test. It's safe to delete a release after it's been made, but we can't remove the versions from PyPI, so maybe make the version number something temporary, like `0.6.7-test-01`. Then when we remove them and make a final version, we can call it `0.6.7` as per usual.

The reason being that PyPI doesn't allow duplicate versions, at all. So again, don't test with a real version number, or else we'll get a gap in our releases - like `0.6.6` to `0.6.12`, once we're done testing and removing releases. Not the end of the world, but if it can be avoided, let's.

Does that make sense?

**Comment by fredrikaverpil** [comment]
Yes, makes a lot of sense. I'd like to go through this together with you thoroughly, since like you say, it's irreversible with PyPi. I'll set up a PR and we'll continue talking there before actually tagging.

**Comment by fredrikaverpil** [comment]
I made a release (`0.6.7`) which turned up almost instantly [in PyPi](https://pypi.python.org/pypi/Qt.py). Then I created release `0.6.8-test-01` but I still don't see that in PyPi.

I wonder if I did things in the wrong order... although I followed [your instructions](https://github.com/mottosso/Qt.py/pull/163#issuecomment-262758170). Where do you see the deployment status?

**Comment by fredrikaverpil** [comment]
Oh, this sucks.

> HTTPError: 400 Client Error: Invalid version, cannot be parsed as a valid PEP 440 version. for url: https://pypi.python.org/pypi
/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/setuptools/dist.py:294: UserWarning: The version specified ('0.6.8-test-01') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.

**Comment by fredrikaverpil** [comment]
Gah, managed to create the release before I commited...

Okay, let's have another try with #167.

**Comment by fredrikaverpil** [comment]
I keep getting this:

> Skipping a deployment with the pypi provider because this is not a tagged commit

I don't understand how to fullfil that requirement. I do a merge with a version bump in Qt.py and then I create a new release with the corresponding tag/version. What am I missing?

**Comment by fredrikaverpil** [comment]
> I keep getting this

Ah, I was looking at the wrong commit, it seems. When looking at the correct one it now seems like it worked fine (although a small error which we've probably had all along).

> Uploading distributions to https://pypi.python.org/pypi
> Uploading Qt.py-0.6.8.dev2.tar.gz
> [================================] 9578/9578 - 00:00:03
> running upload_docs
> creating build
> creating build/docs
> error: no files found in upload directory 'build/docs'
>
> No stash found.
> 
> Done. Your build exited with 0.

**Comment by fredrikaverpil** [comment]
Pip doesn't download the tar.tgz file yet, but downloading that manually from PyPi and then producing a wheel seems like it does indeed work:

```bash
$ pip wheel -w . /Users/fredrik/Downloads/Qt.py-0.6.8.dev2.tar.gz 
Processing /Users/fredrik/Downloads/Qt.py-0.6.8.dev2.tar.gz
Building wheels for collected packages: Qt.py
  Running setup.py bdist_wheel for Qt.py ... done
  Stored in directory: /Users/fredrik/code
Successfully built Qt.py

$ pip2 install Qt.py-0.6.8.dev2-py2.py3-none-any.whl 
Processing ./Qt.py-0.6.8.dev2-py2.py3-none-any.whl
Installing collected packages: Qt.py
Successfully installed Qt.py-0.6.8.dev2

$pip3 install Qt.py-0.6.8.dev2-py2.py3-none-any.whl 
Processing ./Qt.py-0.6.8.dev2-py2.py3-none-any.whl
Installing collected packages: Qt.py
Successfully installed Qt.py-0.6.8.dev2
```

**Comment by fredrikaverpil** [comment]
Pip still doesn't download the tar.tgz hosted in PyPi. Is it possible this is because it's a dev release?

Either way, it now looks like the wheel is universal and we should be able to file a new non-dev release. What do you think?

**Comment by mottosso** [comment]
That's an interesting feature, looks like releases marked `dev` have special meaning to `pip`.

- https://packaging.python.org/installing/#installing-prereleases

You install them using the `--pre` flag.

```bash
$ pip install --pre Qt.py
```

Looks good to me, let's pull the trigger!

**Comment by fredrikaverpil** [comment]
Ah!

That's actually a very nice feature (in our case).

```powershell
$ pip2 wheel --no-cache --pre -w . Qt.py
Collecting Qt.py
  Downloading Qt.py-0.6.8.dev2.tar.gz
Building wheels for collected packages: Qt.py
  Running setup.py bdist_wheel for Qt.py ... done
  Stored in directory: c:\users\iruser\code\repos\qt.py
Successfully built Qt.py

$ dir *.whl
 Volume in drive C is Windows
 Volume Serial Number is 92FF-FCC6

 Directory of C:\Users\iruser\code\repos\Qt.py

11/25/2016  10:18 AM             6,723 Qt.py-0.6.8.dev2-py2.py3-none-any.whl
               1 File(s)          6,723 bytes
               0 Dir(s)  1,807,888,773,120 bytes free
```

So, what do you say, should I just change the Qt.py version into `0.6.8` and create a new `0.6.8` release to make this happen?

**Comment by fredrikaverpil** [comment]
Allright, implemented in #168 🎉 

```
Qt.py-0.6.8-py2.py3-none-any.whl
```

**Comment by mottosso** [comment]
Whop whop! Good job!

**Comment by greatestape** [comment]
Hi everyone. I discovered your repo by chance while trying to solve the universal wheel issue for my project. It looks like we both have the same bug: we put the "distributions" field inside the "on" part of "deploy".

Looking back at the comments here, it looks like travis was never actually building the wheel for you, and I think this is why.

I've submitted a pull request with the fix. I know it's hard to test changes to the "deploy" part of a travis config so you might be hesitant to change it, but I thought I'd offer up this fix anyway, because I found this to be a hard bug to track down.
