### ISSUE TITLE
PIL.ImageQt not picking the right Qt

### ISSUE THREAD

**Issue by melMass** [mottosso/Qt.py#247]
Hello,

I don't know how relevant it is but:
 - The ImageQt.ImageQt(PilImage) function does not pickup the same version as Qt.py (in my case Qt.py chooses to use PySide2 whereas PIL looks for Qt5 Libs)
 - Without Qt.py, PIL do pickup the right version 

I'm not sure how the library detection is done on the PIL side.

**Comment by mottosso** [comment]
Hi @melMass,

PySide2 is using Qt 5 libraries, so that shouldn't be a problem. Did you mean it found PyQt5? If so, you can either (1) change the [preferred binding](https://github.com/mottosso/Qt.py#override-preferred-choice) for Qt.py or (2) remove PyQt5 from your `PYTHONPATH`. It's unwise to keep both bindings available at the same time, as they are incompatible with each other and may cause things to segfault.

**Comment by mottosso** [comment]
Welcome to re-open if the problem persists.
