### ISSUE TITLE
Qt.py

### ISSUE THREAD

**Issue by mottosso** [mottosso/Qt.py#25]
What do you think of making the name more Python-specific?

I figure this would be the GitHub and PyPI name.

```bash
$ git clone https://github.com/mottosso/Qt.py
$ pip install Qt.py
```

But that we'd still import it as we do now.

```python
import Qt
```

**Comment by fredrikaverpil** [comment]
Actually, I've realized we should change the name to avoid confusion. I keep having to write "Qt module" instead of just "Qt" (or in your suggestion "Qt.py") to avoid having readers thing I refer to the actual Qt.

I'm all for your suggestion. I would even go to such length to propose we might want to call it QtWrap or QtAlias or something. But if you feel strongly about Qt.py,  think that's much better than just Qt.

I also wish to keep `import Qt`.

**Comment by fredrikaverpil** [comment]
Hm. Come to think of it... `QtWrap` and `QtAlias` sounds like they could be part of the `Qt` module:

    from Qt import QtAlias

I think `Qt.py` is great! Go for it.

**Comment by mottosso** [comment]
Done!

**Comment by fredrikaverpil** [comment]
Awesome!
