### ISSUE TITLE
Any chance of adding PythonQt?

### ISSUE THREAD

**Issue by twardoch** [mottosso/Qt.py#322]
There is another Python-related Qt project: https://mevislab.github.io/pythonqt/

It looks like its differences are similar in nature to the PyQt-PySide differences. PythonQt has an advantage as it can be embedded nicely into Qt C++ apps (so Python can be used as a scripting lang within a large C++ app).

Any chance you could add support of it? Even just a skeleton, for others to do in the gaps.

**Comment by mottosso** [comment]
What kind of support are you looking for?

At first glance, it looks like another option to PySide, PySide2, PyQt4 and PyQt5? But (briefly) looking at their [features](https://mevislab.github.io/pythonqt/Features.html) page it sounds quite a bit different than either of those; e.g. "not as Pythonic as PySide", no signals, properties instead of setters/getters.

It would be interesting, although it looks like quite the task. It looks like support should instead be added by PythonQt; if they can make it look and act like PySide2, then Qt.py would work as well.

**Comment by mottosso** [comment]
Closing this as missing out on some information, welcome to re-open if/when you see this.

**Comment by twardoch** [comment]
I've opened an issue at the other repo

https://github.com/MeVisLab/pythonqt/issues/8

I think it's fine to keep this one closed. I cannot contribute code myself, and I'm not sure whether this will go anywhere. But it might, and then it probably would make some people happy. 

Thanks!
