### ISSUE TITLE
name 'QGuiApplication' is not defined

### ISSUE THREAD

**Issue by freezePeach** [mottosso/Qt.py#354]
from Qt.QtGui import *
	# screen = QtGui.QGuiApplication.primaryScreen().availableGeometry()

NameError: name 'QGuiApplication' is not defined

works with PySide2 and PyQt5 import

Disclaimer: I'm probably just a noob.

**Comment by mottosso** [comment]
If you go [here](https://doc.qt.io/qt-5/classes.html), and look for `QGuiApplication`, you'll find [this](https://doc.qt.io/qt-5/qguiapplication.html) where it says "Since: | Qt 5.0" and that's no good. Qt.py only contains members in both Qt 4 *and* Qt 5.

For Qt 5-only, see [Qt5.py](https://github.com/mottosso/Qt5.py).

**Comment by johnhaddon** [comment]
I just found myself hitting the same issue, and obviously can work around it without a problem. But I wonder if you think it might be reasonable to drop Qt 4 support in favour of full support for Qt 5 at some point? The last VFXPlatform year to mandate Qt 4 was 2015, so I would hope (perhaps naively?) that it's something we could all leave behind us.

**Comment by mottosso** [comment]
> so I would hope (perhaps naively?) that it's something we could all leave behind us.

I wish. xD

Qt.py will always support (or be limited to, depending on how you look at it) Qt 4 and Qt 5, and from the looks of it Qt 6 too.

If all you need is Qt 5, Qt5.py is a drop-in replacement to Qt.py minus support for Qt 4.
