### ISSUE TITLE
missing: QtGui.QGuiApplication

### ISSUE THREAD

**Issue by DavidShawGL** [mottosso/Qt.py#418]
I am swapping our python tools over to use Qt.py and have an issue with not being able to find QtGui.QGuiApplication

We have a close window function that we try to get topLevelWindows from:
`tops = QtGui.QGuiApplication.topLevelWindows()`

PySide2 and 6 imports of QtGui are able to find QGuiApplication but not when replace the import with Qt.

I'm not sure if I am misunderstanding something though.

Thanks
Dave

**Comment by mottosso** [comment]
QGuiApplication was added in Qt 5 (see "Since:"): https://doc.qt.io/qt-5/qguiapplication.html

Qt.py is still compatible with Qt 4, and thus cannot include members that does not also exist in Qt 4. There is interest in removing Qt 4, given that it isn't very popular these days anyway.

- https://github.com/mottosso/Qt.py/issues/413

It's marked with a #helpwanted and is only missing someone to take the initiative. (hint)
