### ISSUE TITLE
tests: clean function

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#56]
In tests.py, I find the clean function a bit confusing...

Some points:
- Python [does not support unloading modules](http://bugs.python.org/issue9072)
- Nose has this [`--with-isolation`](http://nose.readthedocs.io/en/latest/plugins/isolate.html) option, which does its best to isolate each test function.
- Currently, `sys.modules.pop()` is being used to "clean out" modules, but it doesn't actually clean out modules imported by the module you're popping.

If we just disregard that Python can't "unimport" modules and see how far we can push it... and skip `--with-isolation` since we might not want to isolate all functions –– shouldn't this be a more reliable cleaning function?

```python
import os
import sys
import imp
import contextlib

from nose.tools import (
    with_setup,
    assert_raises,
)

_modules = sys.modules.copy()

def clean():
    """Provide clean working environment"""
    os.environ.pop("QT_PREFERRED_BINDING", None)
    modules_to_delete = list(set(sys.modules) - set(_modules))
    for module in modules_to_delete:
        sys.modules.pop(module)  # or "del sys.modules[module]"
```

Right now, even if you pop `Qt`, the modules imported by `Qt` aren't popped.

Also, with nose, we can create a `tests folder` (rather than the `tests.py` file), and inside it put several python scripts prefixed with `test_` and nose will run all of them.

@mottosso what do you think about this?

**Comment by fredrikaverpil** [comment]
And/or perhaps we *should* use `--with-isolation` and provide `setup` and `teardown` functions in tests.py. I somehow feel this is a more common use case than attempting to "clean" in between tests.

**Comment by fredrikaverpil** [comment]
I'll set up a PR in case you think this is a good suggestion.

**Comment by mottosso** [comment]
> Python does not support unloading modules

This is true, but it isn't really doing that. All it's doing is ensuring that `Qt.py` is re-read at each import and that any variables it reads are reset so that our tests can run it multiple times without affecting each other. It will likely only work in this unique case, and not so much with other modules (did you try with `sip`?).

> And/or perhaps we should use --with-isolation so that each test is indeed supposed to run separately from each other.

As far as I can tell, `--with-isolation` does what you did in your example.

> The isolation plugin resets the contents of sys.modules after running each test module or package. [Link](http://nose.readthedocs.io/en/latest/plugins/isolate.html?highlight=isolate)

But it's a good point. It would be good if each test could be *completely* isolated. As in, being their own process. I'm sure there's an option for this with nose, I just haven't experienced it.

**Comment by mottosso** [comment]
Maybe something like this could enable isolation.

- https://github.com/dmccombs/nosepipe

**Comment by fredrikaverpil** [comment]
Nice find!
PR coming up...
