### ISSUE TITLE
Why do we run tests in Python 3.4 when 3.5 is available?

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#61]
Wouldn't it be better to use the latest version?

https://github.com/mottosso/Qt.py/blob/master/.travis.yml#L8

**Comment by mottosso** [comment]
I started using it because the PySide install I had were only available for 3.4.

- https://github.com/mottosso/Qt.py/commit/296dd44f0e35be24b2c72579af160f07ec09ce6a#diff-354f30a63fb0907d4ad57269548329e3R20

We're using apt-get now, so it won't matter. But 3.4 is the default interpreter in Ubuntu 14.04, the one we use for Travis, so I'd stick with that. It's better to test with older versions, because the likelyhood if it working with a newer is bigger than if we try with a newer and hope it works in an older.

Speaking of which, we should get 2.6 in there too.

**Comment by fredrikaverpil** [comment]
Ok, makes sense!

> Speaking of which, we should get 2.6 in there too.

You mean adding 2.6 and still leaving 2.7 in there, right?

**Comment by mottosso** [comment]
Yes, no harm in testing too much.
