### ISSUE TITLE
How to test docstrings of Qt.py?

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#85]
As mentioned [here](https://github.com/mottosso/Qt.py/pull/81#issuecomment-236665431).

Example:

``` python
>>> from Qt import load_ui
>>> class MyWindow(QtWidgets.QWidget):
...    def __init__(self, parent=None):
...        fname = 'my_ui.ui'
...        load_ui(fname, self)
>>> window = MyWindow()
```

**Comment by fredrikaverpil** [comment]
We can re-open this if we feel this is a priority.

**Comment by mottosso** [comment]
To answer the question, the trick is to make functionality that can be tested shortly.

For example, rather than a function taking a file-path, it could take the contents of a file. That would allow a doctest to pass mock contents, rather than (1) making a file on disk, (2) passing this file to the function and (3) cleaning the file up afterwards.
